# Generated by Django 6.1.1 on 2026-09-11 22:49

import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0098_apitoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurismoPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Texto de presentación que aparece arriba de los destinos.', verbose_name='Introducción')),
            ],
            options={
                'verbose_name': 'Página de Turismo',
            },
            bases=('wagtailcore.page',),
        ),
    ]
