# Generated by Django 6.1.1 on 2026-09-11 22:01

import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0098_apitoken'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticiaIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Texto breve opcional que aparece arriba del listado.', verbose_name='Introducción')),
            ],
            options={
                'verbose_name': 'Índice de noticias',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NoticiaPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('fecha', models.DateField(verbose_name='Fecha de publicación')),
                ('categoria', models.CharField(choices=[('institucional', 'Institucional'), ('beneficios', 'Beneficios'), ('gremiales', 'Gremiales'), ('comunidad', 'Comunidad / Efemérides')], default='institucional', max_length=20, verbose_name='Categoría')),
                ('copete', models.CharField(blank=True, help_text='Resumen breve que aparece en el listado y en los buscadores.', max_length=300, verbose_name='Copete')),
                ('body', wagtail.fields.RichTextField(blank=True, verbose_name='Cuerpo')),
                ('imagen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen destacada')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
            },
            bases=('wagtailcore.page',),
        ),
    ]
